---
# ===========================================
# POSTGRESQL ROLE - STUDENT LEARNING EXERCISE  
# ===========================================
#
# This is a MINIMAL starter. You need to EXTEND it with:
# 1. Database creation (webapp_db)
# 2. User creation (webapp_user with password)
# 3. Basic schema (users table with id, name, email)
# 4. Permissions setup (GRANT statements)
#
# LEARNING GOALS:
# - Learn PostgreSQL administration
# - Learn database user management
# - Learn SQL schema creation
# - Learn Ansible postgresql modules
# ===========================================

# TODO: Add database creation task
# TODO: Add user creation task
# TODO: Add schema creation task
# TODO: Add permissions setup

- name: "Install postgresql package"
  package:
    name: postgresql
    state: present

- name: "Start postgresql service"
  service:
    name: postgresql
    state: started
    enabled: yes
