apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: week21-app
  labels:
    app: backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: backend
    spec:
      containers:
      - name: flask-app
        image: week21-backend:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_NAME
          value: "app"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "secret"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
