apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: week21-app
  labels:
    app: backend
    component: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP
