---
# ===========================================
# NGINX ROLE - STUDENT LEARNING EXERCISE
# ===========================================
# 
# This is a MINIMAL starter. You need to EXTEND it with:
# 1. SSL certificate generation (openssl commands)
# 2. HTTPS configuration (nginx.conf template)
# 3. Virtual hosts support (multiple sites)
# 4. Security headers and optimization
#
# LEARNING GOALS:
# - Learn Ansible template module
# - Learn SSL certificate generation
# - Learn nginx configuration syntax
# - Learn virtual hosts setup
# ===========================================

# TODO: Add SSL certificate generation task
# TODO: Add nginx configuration template task  
# TODO: Add virtual hosts configuration
# TODO: Add security headers

- name: "Install nginx package"
  package:
    name: nginx
    state: present

- name: "Start nginx service"
  service:
    name: nginx
    state: started
    enabled: yes
