# ===========================================
# VAGRANT CONFIGURATION FOR WEEK 15 HOMEWORK
# ===========================================
#
# Two test VMs for comparing Ansible vs Puppet
# - ansible-vm: Test your Ansible implementation
# - puppet-vm: Test your Puppet implementation
# ===========================================

Vagrant.configure("2") do |config|
  # Base box for both VMs
  config.vm.box = "ubuntu/jammy64"
  
  # Ansible test VM
  config.vm.define "ansible-vm" do |ansible|
    ansible.vm.hostname = "ansible-test"
    ansible.vm.network "private_network", ip: "192.168.56.11"
    
    # VM resources
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Shared folder for Ansible code
    ansible.vm.synced_folder "../ansible", "/vagrant/ansible"
  end
  
  # Puppet test VM
  config.vm.define "puppet-vm" do |puppet|
    puppet.vm.hostname = "puppet-test"
    puppet.vm.network "private_network", ip: "192.168.56.12"
    
    # VM resources
    puppet.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Shared folder for Puppet code
    puppet.vm.synced_folder "../puppet", "/vagrant/puppet"
  end
end
